### ISSUE TITLE
How to set the test mode while making OAuth payment?

### ISSUE THREAD

**Issue by boryn** [mollie/laravel-mollie#167]
I use the test .env MOLLIE_KEY beginning with 'test_', but it's not enough while doing authentication through OAuth - it's necessary to pass the 'testmode' parameter. I can see in the code:
```php
$options["testmode"] = $this->mode === "test" ? true : false;
```
but how to set the `$this->mode`? There is no `setMode()` method and while issuing:
```php
$payment = Mollie::api()->payments->create([
// ...
```

there is no place to set the mode either.

**Comment by sandervanhooft** [comment]
**Please note**
For normal webshop integrations, you will not need OAuth and it's far easier to use the default authentication - using keys. If this is the case, you simply use the `test_` key for testing interactions with Mollie and swap it out when you're ready to go live.

If you however have more advanced use cases and/or need to act on behalf of other Mollie accounts, you will need OAuth.

**Regarding your questions**

1. you cannot use the `test_` key with Oauth. You'll need the app secret and app id keys. More info [here](https://github.com/mollie/laravel-mollie/blob/master/docs/mollie_connect.md).

2. In order to use OAuth testmode you need to pass it in on each request you make:

```php
$payment = Mollie::api()->payments->create([
    "testmode" => true,
    // ...
]);
```

In the [Mollie API reference](https://docs.mollie.com/reference/v2/payments-api/create-payment) you can see at the very top which API endpoints support OAuth authentication ("App access tokens").

**Comment by boryn** [comment]
Thank you for your reply!

This is the application which already uses OAuth. We are implementing some new features and wanted to use the test environment. 

Passing `"testmode" => true,` to `Mollie::api()->payments->create()` helped! (I suggest adding this example to the documentation, I could not figure it out).

**Comment by boryn** [comment]
If you stumble upon this thread, here it is how to pass the testmode to the get() method:
```php
$payment = Mollie::api()->payments()->get($payment->id, ['testmode' => true]);
```

In case you get error, check if you had set the access token above:
```php
Mollie::api()->setAccessToken($accessToken);
```
