### ISSUE TITLE
Composer require conflicts

### ISSUE THREAD

**Issue by iH8** [mollie/laravel-mollie#188]
## Specifications

  - API Version: 2
  - Laravel Framework Version 8.78.1

## Describe the issue

I'm running: `composer require mollie/mollie-api-php:^2.0` and getting the following error: ` mollie/laravel-mollie v2.0.0 requires illuminate/support ^5.5 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev] but it conflicts with another require.` I've upgraded Laravel which works, i am now running 8.83.2. But it still gives the same error. I've installed no other packages, just trying to install Mollie so i'm kinda baffled as to why this happening.

**Comment by sandervanhooft** [comment]
@iH8 I've transferred the issue to the laravel mollie repo.

I just ran your `composer.json` file and it install fine now. Perhaps one of the dependencies has been upgraded. Can you check if it works for you now?

If not ...

The warnings you are seeing are throwing me off a bit, as if the version constraint is not parsed correctly.

Therefore, instead of installing it through the commandline, add the dependency to your composer.json file and then run `composer update`.

```php
"mollie/laravel-mollie": "^2.0"
```

**Comment by iH8** [comment]
I don't know why i filled this under the wrong repository, sorry, thanks for transferring it. I've tried the composer install again, still a no go, with the same error. However manually adding it to composer.json and then update does work for me. I didn't even think to try that, i assumed it would result in the same error. My bad, thanks for the tip.

**Comment by sandervanhooft** [comment]
I suspect it may be because of syntax differences between Windows/Linux/Mac commandlines.

Anyway, glad it worked out! Enjoy!
