### ISSUE TITLE
422: Unprocessable Entity: No suitable payment methods found

### ISSUE THREAD

**Issue by divdax** [mollie/laravel-mollie#194]
I'm testing the mollie api. Payment methods like PayPal is activated but has to be reviewed. The review is not possible because the project is not online yet... How i can test the payment?

**Comment by sandervanhooft** [comment]
Hi @divdax,

Any payment method that is activated by you can be tested using a test key. Even if they're still under review.

Local testing of the webhook functionality is possible if you use a (free) tunneling service.

Options for Laravel/PHP include:

- `valet share`
- Expose by Beyond Code
- ngrok

https://docs.mollie.com/overview/testing

**Comment by divdax** [comment]
@sandervanhooft i use a tunneling service so mollie can reach my webhook endpoint.
Using the test api key and activated PayPal as payment method. (under review)

API response:
```
Error executing API call (422: Unprocessable Entity): No suitable payment methods found. Documentation: https://docs.mollie.com/overview/handling-errors
```

**Comment by divdax** [comment]
@sandervanhooft
1. Yes i'm using the correct test key from my account.
2. 4 Payment Methods are activated but under review.

**Comment by sandervanhooft** [comment]
Hi @divdax ,

I was unable to reproduce your issue with the snippet below - everything is working fine here.

```php
mollie()->payments->create([
  "description" => "PayPal Test Payment",
  "amount" => [
    "value" => "12.34",
    "currency" => "EUR",
  ],
  "redirectUrl" => "https://www.mollie.com",
  "method" => \Mollie\Api\Types\PaymentMethod::PAYPAL,
]);
```

If this doesn't work for you, could you please reach out to Mollie support?

**Comment by divdax** [comment]
@sandervanhooft  Now i get this response:
```
Error executing API call (422: Unprocessable Entity): Your account is currently suspended
```

mollie support said i have no website online to activate payment methods etc. but i just want to test the api without going live with that. I don't have any website online yet, because we are testing... bad support, no reactivation event not for testing... WOW! 👏

**Comment by sandervanhooft** [comment]
I am sorry to hear that. Mollie indeed does require a website url - but for testing any will do.

This seems to be very account specific, so I am afraid I cannot be of further assistance on this matter.

**Comment by Timollie** [comment]
@divdax 
I am sorry to hear you are experiencing issues whilst trying to create test payments. As @sandervanhooft said, requesting a payment method should almost always allow you to do test payments whilst the methods are still being reviewed.

We have on our backlog to implement development specific organisations on which only test payments can be done so that the normal onboarding procedures would not be required. However, I do not have a concrete timeline for this.

For now, if could either share your organisational ID or a support ticket number I can have a look at what I can do for you.

Sorry for the inconvenience.

**Comment by divdax** [comment]
@Timollie
Thank you. Maybe you can check my account #3559744 and revoke the suspend status which causes the problem?

**Comment by Timollie** [comment]
@divdax,
Thank you. I had a quick look. Indeed your website profile has been suspended by my colleagues over at onboarding. This was done since the website doesn't exist yet. I would advise creating a new website profile, there are no costs to this, and calling it something like "Testing" or "Staging". If you do not process live payments through this my colleagues should not block the payment methods. I also made a note in our backend of this.

We know that this is pretty annoying to deal with.. In the past it honestly was less of a problem as our backlog on onboarding was significantly larger. Nowadays my colleagues get to checking really quickly. We are working on a better solution, like true test profiles, but I can not provide concrete timelines for that yet.

Please let me know if you have any further questions.

**Comment by Timollie** [comment]
My colleagues also unblocked your existing profile.

**Comment by divdax** [comment]
@Timollie thank you! The test api key is working now.
