### ISSUE TITLE
Integrate in cashier?

### ISSUE THREAD

**Issue by mario** [mollie/laravel-mollie#20]
Any thoughts on integrating this directly in Cashier?

**Comment by FaaPz** [comment]
Hi @mario, unfortunately not. Laravel Cashier is very interesting though, so we might look into it in the near future.

**Comment by ruudschuurmans** [comment]
This would be awesome!

**Comment by stefro** [comment]
+1 if this would be integrated.

**Comment by sigfriedseldeslachts** [comment]
+1

**Comment by stefanpkc** [comment]
+1

**Comment by kayyyy** [comment]
+1

**Comment by rbenjamint** [comment]
+1

**Comment by ItsDizzy** [comment]
I am working on a Laravel Cashier edition for Mollie, if anyone would like to help it would be very appreciated. Project is here: https://github.com/ItsDizzy/laravel-cashier-mollie

**Comment by Treggats** [comment]
@fpaapz is the future near enough for the integration?

**Comment by Olindn** [comment]
Any update on this matter?

**Comment by petericebear** [comment]
Would love to see an update on this as well.

**Comment by willemstuursma** [comment]
We're looking for a freelancer who can integrate Mollie into Cashier for us. Please send any recommendations to willem@mollie.com.

**Comment by sandervanhooft** [comment]
Right now this package is being upgraded to use the new Mollie-PHP client (v2) and its new features.

Once completed we'll look into the possibilities of using Mollie with Laravel Cashier.

Personally I am not convinced yet it is possible though ([my thoughts, June 2017](https://www.sandervanhooft.com/blog/laravel/when-laravel-cashier-will-not-help-you/)), as Cashier is rather tightly coupled with Stripe and Braintree.

But I hope I'm wrong.

If you come across any relevant information on using Laravel Cashier with Mollie, please post it here.

**Comment by sandervanhooft** [comment]
Just finished a quick scan of Laravel Cashier, for Stripe and Braintree. Here's what I found.

### In general / both projects
- Started and maintained by the Laravel core team
- Primary goal is subscription management (not one-off payments)
- Despite the 'Cashier' naming, the Stripe and Braintree are two completely separated packages. I.e. there's no `laravel/cashier-core` dependency.
- Cashier for Stripe was developed first. Braintree support was added later.
- Stripe and Braintree dependencies are rooted deeply in the Cashier core(s). That's why they probably have decided to maintain two completely separate projects.
- The official docs mention Cashier Braintree's limits (vs Stripe). The Stripe implementation is considered the default.

### Default Cashier (Stripe)
- 1.4 million downloads (packagist.org)
- Actively maintained

### Cashier Braintree
- 124k downloads
- V2.0, but still in "beta"
- Not really actively maintained (version bump 5 months ago)

### Cashier Mollie (?)
So, a Mollie variant would be a third independent variant. Despite the maintenance downside of not sharing a core with other implementations, there's room for maneuverability to things work.

A number of things to consider...
Cashier Stripe and Braintree:
- are creditcard based.
- use payment tokens and allow payments to be processed completely via their APIs. Mollie leverages redirects to payment screens and then back to the application. This means some functionality will need to be split / altered.
- use their respective APIs for subscription management. Mollie has a subscription API as well, but seems to favor recurring payments.
- use their respective APIs for coupon/discount management. AFAIK Mollie does not support this. So this should be handled locally (in the package).
- use their respective APIs for trial period management. AFAIK Mollie does not support this. A delayed subscription start date is no option if the payment method requires a mandate payment

Ideally some coordination occurs with the Cashier core team for promotional reasons. The Cashier team is a large factor for successful developer adoption of Cashier Mollie.

**Comment by sandervanhooft** [comment]
Perhaps we can leverage the [Laravel-promocodes](https://github.com/zgabievi/laravel-promocodes) package for the discount code features.

**Comment by sandervanhooft** [comment]
Personally I have used Laravel Spark in the past, but dropped it in the end because it wasn't that interesting for the European market (no translation support, creditcard / paypal only).

**Comment by nickurt** [comment]
I just found this (starting, wip) repo (in case you didn't saw/found it yet), maybe you guys can collaborate on this matter

https://github.com/runlinenl/dutch-cashier

**Comment by sandervanhooft** [comment]
Last week we were at Laracon.eu. Talked to a lot of Laravel enthousiasts.

And with Taylor Otwell ofcourse.

If the proof of concept goes well, he's happy to accommodate us in the official Laravel docs when we're ready for stable release! 🎉

Right now we're busy finalizing work on the Orders & Shipments API and support for Klarna. It's in beta now.

In the meantime, we're working on Cashier on the side. Expect to go deeper on this in the coming weeks.

**Comment by joshuadegier** [comment]
Sounds good! I'll keep an eye on this and I'm willing to use my Spark license to do some beta testing. For the record: I've got no active Spark SaaS application running right now, it'll be in a testing environment.

**Comment by sandervanhooft** [comment]
Thanks @joshuadegier !

Note that we're working on _Cashier_ now, if things go well _Spark comes after that_.

That being said, it reminds me I should update my existing Spark license when I am ready integrate Cashier Mollie into Spark.

**Update**: I am working on a _second_ Alpha for Cashier these weeks. Behind the scene's I happily killed off the first alpha. Happily - because I learned a lot about all different Cashier packages, Mollie (and other PSPs') APIs.

The first alpha was built on the Mollie Subscriptions API (scheduling payments Mollie-side). This API is great for its ease of use, but not flexible enough to support the advanced Cashier features like handling discounts, swapping plans, prorating, etc.... That essentially would be all the nice features that make Cashier awesome. We can do much better than leaving these features out.

By providing a solution that schedules (triggering) the payments at the merchant side we will be able to support all the nice Cashier features with SEPA directdebit and (later) creditcard. While also keeping an eye on even more advanced features like supporting multi-plan and metered billing (which are not available yet in other Cashier packages).

We now have the opportunity to lay the groundwork for this, so we better take it. 😄

I've worked out the new package architecture and am fleshing out the groundwork right now.

Expect an alpha release about a month from now.

It will be a bit limited in scope (i.e. leaving out discount handling, SEPA directdebit only) but the architecture is prepared for additional features to be plugged in without having to run complex database migrations in your application.

**Comment by nick076** [comment]
Do you have any update Sander? Would love to hear something. 👍

**Comment by sandervanhooft** [comment]
@nick076 et al

Working on the last bits for the alpha release...

**Comment by sandervanhooft** [comment]
Here's my current backlog:
- [x] Flexible architecture for adding discount handling in the future
- [x] Flexible architecture for adding metered subscriptions in the future
- [x] Flexible architecture for adding one-off items in the future
- [x] Define and retrieve subscription plans
- [x] Process Order Items into an Order (not yet integrated with Mollie)
- [x] Processing an orderItem empties subscription->scheduledOrderItem
- [x] Check empty(subscription->scheduledOrderItem) before scheduling a new orderItem
- [x] OrderNumberGenerator (Sequential)
- [x] Post processing Order Items (incl scheduling new Order Items) 
- [x] Create a subscription (mandated customer)
    - [x] Yields an Order Item on start
    - [x] Postprocessing an Order Item schedules next Order Item.
- [x] Cancel a subscription
- [x] Swap a subscription's plan
- [x] Subscription->scheduleNewOrderItem fills instead of updates $this
- [x] Prorating yields an additional negative OrderItem
- [x] VAT handling (User -> OrderItem)
- [x] Trial periods
    - [x] A generic trial without mandate upfront
    - [x] A trial period with mandate upfront. Schedules an orderItem to be processed at end of trial period.
        - [x] SubscriptionBuilder->trialUntil(x)
        - [x] Adjust Billable.onTrial()
        - [x] SubscriptionBuilder->trialDays(x)
        - [x] Canceling the subscription removes the scheduled orderItem.
- [x] Generate an invoice for order
    - [x] Use a separate invoice generator, so we can create it on the fly without persisting. Handy for generating upcoming (projected) invoices
    - [x] startingBalance
    - [x] completionBalance
    - [x] Add a note to an order/invoice
    - [x] Invoice->view()
    - [x] Invoice->pdf()
    - [x] Invoice->download()
    - [x] Connect to Order model
    - [x] Connect to OrderCollection model
    - [x] Connect to Billable trait
    - [x] Item descriptions:
        - [x] Subscription.getDescription()
        - [x] -> OrderItem.description
        - [x] -> Invoice
    - [x] Template (Use Stripe template for now) (test manually)
    - [x] Process owner balance in invoice
- [x] Truly polymorphic owner/billable relationship. Remove `user_id` references.
- [x] Static order item postprocessor call
- [x] Remove Mollie OrderBuilder
- [x] CamelCase test cases
- [x] Check whether customer has appropriate mandate before creating a subscription
- [x] Timestamp migration stubs on publishing
- [x] Process user credits in Order (keep a balance)
- [x] Handle orders with Mollie
    - [x] If total_due = 0
        - [x] Do nothing
    - [x] If total_due > 0
        - [x] Create Mollie payment
        - [x] Correctly configure webhookUrl
    - [x] If total_due < 0:
        - [x] if the user still has an active subscription in same currency, add credit to the user balance
        - [x] else issue refund(s)
            - [x] Throw an Exception if unable to refund.
- [x] Remove billable model from Cashier/config
- [ ] Webhooks, i.e. handling failed payments
    - [ ] ? HandleFailedPayment on OrderItem triggers HandleFailedPayment on Subscription
        - [ ] handlePaidPayment vs handleFailedPayment
            [ ] should be in InteractsWithOrderItems contract
- [ ] Define contract(s) for the Owner model:
    - [ ] `getInvoiceInformation()`
    - [ ] `getExtraBillingInformation()`
- [ ] 95%+ test coverage
- [ ] Test app manually
- [ ] Documentation
    - [ ] You **must** implement `getInvoiceInformation()` on the Owner model.
    - [ ] You _can_ implement `getExtraBillingInformation()` on the Owner model.

**Comment by sandervanhooft** [comment]
This stuff is for later:

# Later
- [ ] Store Order details (= Mollie Order payload) on payment metaData
- [ ] Swap mandate (similar to "swap cards") <- store preferred mandate id on Owner model
- [ ] Check db transactions:
    - [ ] Transaction scopes ok?
    - [ ] Require more transactions?
- [ ] Dynamically bind OrderNumberGenerator
- [ ] Dynamically bind Cashier
- [ ] Extract Mollie/Laravel-Cashier-Adapter (Incl. Invoice)
- [ ] Use Plan repository and support custom Plan classes / Config defaults helpers (cascading defaults)
- [ ] Create a subscription for a not-yet-mandated customer via a mandate payment screen -> probably using balance
- [ ] Add balance
- [ ] Balance metrics
- [ ] Refunds
- [ ] One Off payments
- [ ] Order->processNow()
- [ ] Possibility of advanced Plan calculations with dedicated Plan Classes
- [ ] Subscription quantity
    - [ ] Set upon creation
    - [ ] Update when after subscription has started (requires prorating option)
- [ ] Discount handling
- [ ] Subscription discounts
- [ ] Add credit card payment method
- [ ] Metered subscriptions
- [ ] Calculate received tax for accounting, tax reporting
- [ ] Implement "cashier:install" and/or "cashier:upgrade" artisan command

**Comment by sandervanhooft** [comment]
Thanks for sharing the enthusiasm!

**Comment by Treggats** [comment]
Awesome work so far, count me in for the beta

Op do 22 nov. 2018 18:23 schreef Sander van Hooft <notifications@github.com:

**Comment by sandervanhooft** [comment]
@Treggats Thanks! You mean the alpha? 😄

**Comment by JoeriAben** [comment]
Would be nice to join the alpha testing group and help improve the package.

**Comment by Treggats** [comment]
Whoops, yes the alpha🐒

Op do 22 nov. 2018 18:58 schreef Sander van Hooft <notifications@github.com:

**Comment by petericebear** [comment]
I would like to join that group :)

**Comment by sandervanhooft** [comment]
@nick076 
@Treggats 
@JoeriAben 
@petericebear 

You can expect the invite in a minute. ✉️

**Request:** It would be of great help if you can give the package a try by letting it run some subscriptions for a while and check if it behaves as expected over time.

**Comment by sandervanhooft** [comment]
If there's any issues, questions,suggestions etc. please open an issue there.

**Comment by sandervanhooft** [comment]
Also, feel free to retweet this so we can extend the test group a bit: https://twitter.com/SandervHooft/status/1068160537106833412

**Comment by milo526** [comment]
Hello, I would also like to explore the possibilities of laravel-cashier if possible.

**Comment by BasMulders** [comment]
Can't wait to play around with Cashier in combination with Mollie. I'd like to receive an invite as well. Thanks!

**Comment by petericebear** [comment]
I will test this week with some subscriptions :D

**Comment by larskoole** [comment]
Hey, finally found some time to reply since @robindirksen1 tweeted you. Could I get an invite for the alpha?

**Comment by nickurt** [comment]
Can I get an invite aswell?

**Comment by sandervanhooft** [comment]
For the invitees: could you help me by replying to this "First impressions" thread?

I'm drafting the plans for the next release, would love your input.

It's here: https://github.com/mollie/laravel-cashier/issues/4

**Comment by tdgroot** [comment]
@sandervanhooft I would like to be invited as well!

**Comment by WebWeave** [comment]
@sandervanhooft would love to be invited and give it some tests.

**Comment by mbardelmeijer** [comment]
@sandervanhooft beta invite would be appreciated here as well :)

**Comment by ruthgeridema** [comment]
@sandervanhooft would like a beta invite as well!

**Comment by KumaVolt** [comment]
@sandervanhooft, Would love to receive a alpha/beta invite as well

**Comment by Beaudinn** [comment]
@sandervanhooft, Would love to receive a alpha/beta invite as well

**Comment by sandervanhooft** [comment]
To all newcomers, be sure to share your first impressions [here](https://github.com/mollie/laravel-cashier/issues/4).

If you want to dive a bit deeper, I could your input [here](https://github.com/mollie/laravel-cashier/issues/20).

**Comment by pascualstromsnes** [comment]
@robindirksen1  Oh, sorry. I didn't know that. I have noe applied for access, so that must be the reason. Thank you!

**Comment by sandervanhooft** [comment]
@pascualstromsnes I've sent you an invite.

**Comment by sandervanhooft** [comment]
Great to here from you @pascualstromsnes ! Some interesting thoughts you're sharing here.

Here's my take...

The Laravel Cashier packages are primarily intended for _subscription_ billing.

After working with Stripe, Braintree and Mollie integrations (incl Spark) I've experienced that solutions like OmniPay are unlikely to ever cover these recurring billing requirements for all sorts of payment methods, by different PSPs (Payment Service Provider), in all regions. It's both too much payment-method specific and too much region-specific. There's too much PSP-unique logic involved to build a truly generic recurring billing solution that is of any value - I agree that it's unfortunate for us integrators.

It's also why I believe this project is promising. Mollie is expanding her services throughout Europe and offers a wide range of payment methods. For recurring payments both creditcards and SEPA are supported in Cashier Mollie. Other ones (PayPal?) may be introduced later on (recurring PayPal is not yet supported by Mollie). So we'll be able to accommodate a lot of use cases, for wherever your customers are, Norway included :).

I noticed the PR to introduce _metered billing_ into Cashier Stripe was also closed.
I'm preparing Cashier Mollie now to accommodate metered billing later on. Will be fun.

**Comment by chefbuitenhuis** [comment]
@sandervanhooft I'm currently working on something with Spark and I'd love to join test group for the Cashier package.

**Comment by sandervanhooft** [comment]
@chefbuitenhuis , I'll invite you in a sec, but please note that this package does not (yet) cover integration with Spark.

**Comment by MSnoeren** [comment]
@sandervanhooft I'm currently working on a PaaS application (not Spark) with subscriptions and would like to test/have access too. Can I be invited as well?

**Comment by ufeg02** [comment]
Can I also get an invite?

**Comment by sandervanhooft** [comment]
FYI I'm working on the next alpha release, which will have some breaking changes compared to the current `master` branch. I plan to release it by the end of this week.

You can already check the `alpha_2` branch (WIP).

**Comment by Fossil01** [comment]
Great stuff. Cannot wait for this to be integrated :-D

**Comment by EZstagetwee** [comment]
I would very mutch like an invite!

**Comment by jaap115** [comment]
Me to. Can I still get invites?

**Comment by nathanverduyn** [comment]
Can I get an invite? Thank you!

**Comment by skalero01** [comment]
Can I get an invitation please?

**Comment by peterjaap** [comment]
:raised_hands:

**Comment by lexdewilligen** [comment]
> Thank you all for the interest!
> 
> The Cashier Mollie Beta will be publicly released at the end of May.
> 
> As we're busy preparing this launch, the alpha Cashier repository no longer accept new invites.
> 
> Keep an eye out for official Laravel news :).

It's end of may now, any news on the launch date?

**Comment by robindirksen1** [comment]
he tweeted yesterday this: https://twitter.com/SandervHooft/status/1133055603167977473

"On it! Will tweet when it’s available later this week."

> > Thank you all for the interest!
> > The Cashier Mollie Beta will be publicly released at the end of May.
> > As we're busy preparing this launch, the alpha Cashier repository no longer accept new invites.
> > Keep an eye out for official Laravel news :).
> 
> @sandervanhooft It's end of may now, any news on the launch date?

**Comment by sandervanhooft** [comment]
Nearly there.

I'm ironing out some things that are hard to change once released into the wild. 🐘🦁

**Comment by sandervanhooft** [comment]
Ok, so this is what's changing with the release:

- package name is now `laravel/cashier-mollie` instead of `mollie/laravel-cashier`. Update your `composer.json` to reflect this. All namespacing in your php files remains the same (`Laravel\Cashier`).
- `PlanRepository::all()` is now a `protected` method. As with other Cashier implementations, use hardcoded references to the plans.
- Added artisan commands `cashier:install` and `cashier:run`.
- The `FixedDiscountHandler` now takes a Mollie-like amount array as context, and you can configure how to handle a discount surplus.

**Comment by sandervanhooft** [comment]
We went live yesterday evening!

The repo (and docs for now): https://github.com/laravel/cashier-mollie

My introductory blog post: https://www.sandervanhooft.com/blog/laravel/laravel-cashier-mollie-is-here/

Enjoy!

**Comment by ricoxor** [comment]
> It's a bit optimistic at this point, but...
> 
> When / if Cashier-Mollie would be released, integration with **Laravel Spark** comes into view, as it relies on Cashier.
> 
> So I will put Laravel Spark research on the Laravel-Mollie roadmap.
> 
> [Laravel Spark](https://spark.laravel.com) is a commercial SAAS starter kit. By adding Cashier-Mollie support, new SAAS projects can be built rapidly on top of Mollie's subscription services.
> 
> As Mollie is currently researching Cashier-Mollie feasibility (and by extent Spark), be sure to let us know if you would use Laravel Spark with Mollie.

Hello,
I really wish I could use Mollie on Laravel Spark. +1

**Comment by peterjaap** [comment]
@ricoxor at Laracon EU 2019, @sandervanhooft announced he would be releasing Cashier-Mollie for Spark soon (this year in any case).

**Comment by sandervanhooft** [comment]
Confirmed!

https://twitter.com/SandervHooft/status/1168838823951896576
