### ISSUE TITLE
Can't invoke webhook and getting empty array as response in "responseUrl".

### ISSUE THREAD

**Issue by GencBlakqori** [mollie/laravel-mollie#3]
Hi,

I don't know if this is really an laravel issue, but I can't make it work.
1) I constantly getting this on the mollie website when I wan't to insert a webhook link:
 _**"Mollie can not invoke the test webhook."**_
Now I have a _Post_ route that invokes a method in my controller, that basically has nothing on it, no checks no nothing. Even if I only do a 200 response, I still get that message on the mollie website.

2) When I'm not using the webhook, just simply create payment, after payment is finished, the redirectURL gets invoket, but as a response I get nothing. When the response route is a _POST_ route, then I get a _Method not allowed_ error. But if i switch it to _GET_, I simply just get an empty array as a response.

**Comment by FaaPz** [comment]
Hi @GencBlakqori, could it be that the webhook link is a URL for your development/test environment that's not connected/reachable by a domain name via the internet? Because that would be the reason why you're getting the *"Mollie can not invoke the test webhook."* message.

The `redirectUrl`-parameter is not the same als the `webhookUrl`. After the payment is completed or canceled, the URL given in the `redirectUrl`-parameter simply redirects you without any query string, post parameters etc. given by Mollie. The `webhookUrl` is triggered as soon the payment's status changes.

I suggest you have look at our documentation:
- https://www.mollie.com/en/docs/reference/payments/create
- https://www.mollie.com/en/docs/webhook

Let us know if you're still struggling! 😉

**Comment by GencBlakqori** [comment]
@FaaPz  Thanks for your response. No, the domain for the webhook is actually reachable, its in on an online server. It just keeps me telling that, I have no idea why, already read the links before I asked you the questions but still can't get it to work. Is there anything special that I have to do with that webhook to make it work ?

**Comment by FaaPz** [comment]
@GencBlakqori I'll look into it! Could you send me (fabian@mollie.com) your partner ID and the failing webhook URL?

**Comment by GencBlakqori** [comment]
The issue has been solved, it was due to the csrf token of laravel. I had to remove that from the webhook root in order to make it work.
@FaaPz  Thank you very much for your support.

**Comment by RicardoJ** [comment]
Thank you for the update. Do you have a example code we can include in the [README.md](https://github.com/mollie/laravel-mollie/blob/master/README.md) for other possible people who have this problem in the future?

**Comment by GencBlakqori** [comment]
Yep so basically, if you have a route like this :
`
Route::post('webhook-link', function($paymentId){
      // whatever check comes here
});
`

,you have to also disable CSRF check for this link in VerifyCsrfToken.php  in the middleware folder. You have to put a variable like this :

`
protected $except = [
        'webhook-link'
 ];
`

( NOTE: This works for Laravel 5.2. I haven't tried it in older versions.)

**Comment by RicardoJ** [comment]
Thanks for the solution. I'll add it to the readme.
